### PR TITLE
add check create/mgmt and refactor

### PR DESCRIPTION
**Pull request by maier**
resolved non-existent conflict (guess it just wanted double confirmation that the changes to circonus-gometrics.go were intentional), re-run short test, commit.

### CODE REVIEW

**Comment by peterbourgon** [comment]
This change broke my builds in go-kit/metrics/circonus. Apparently it completely removed all of the metrics types? I wasn't able to suss out an easy migration plan, because the code is completely undocumented :( Is there a motivating issue or design doc for these changes?

**Comment by maier** [comment]
Where can I get access to go-kit/metrics/circonus to take a look at how it is being used and how best to go forward with the requested ability to automatically create and manage checks.

**Comment by peterbourgon** [comment]
https://github.com/go-kit/kit/blob/8fd6486063b3c3a78ec60ee43f80e80cf7c46374/metrics/circonus/circonus.go

**Comment by maier** [comment]
Not sure I've done this right (any feedback would be appreciated). I tried to model it after the other metric conduits I found in the go-kit/kit/metrics directory. Let me know if I'm warm.

https://github.com/maier/cgm-gk

**Comment by peterbourgon** [comment]
OK, I get it. Looks straightforward. I'll re-add when I find some moments.

**Comment by maier** [comment]
thanks @peterbourgon 

i'm adding comments to the code and more prose in the README. this is still a WIP so, i really appreciate your understanding and patience as i'm working through addressing all of the objectives.

**Pull request merged**
