### PR TITLE
Update dependencies to latest ones

### PR DESCRIPTION
**Pull request by h8liu**

### CODE REVIEW

**Comment by h8liu** [comment]
`go get` build breakage found by [gopkgs.io](https://gopkgs.io):

https://gopkgs.io/builds/20181126-174306-49fa6dfa

**Comment by maier** [comment]
I think a better fix for this is to start using the released version that has now started appearing on the retryablehttp repository. Rather than continuing to track master.

**Comment by jefferai** [comment]
Asking for this to be merged, as it breaks downstream projects that use this lib and also go-retryablehttp and need fixes in that.

**Comment by maier** [comment]
@jefferai both the v2 branch and the v3 branch have the fixes. Please do not track the master branch in your project. The v3 branch will be merged in the near future.

**Comment by jefferai** [comment]
Didn't even know about those branches. Thanks.

**Comment by jefferai** [comment]
@maier Unfortunately, `v2` doesn't contain this fix, and `v3` is broken if you can't yet use go modules.

**Comment by maier** [comment]
Mine v2 still works. I just noticed that there are a couple of patch updates to retryable, i'll update it to use 0.5.2 maybe that will help you.

**Comment by jefferai** [comment]
Right, the isuse is that if you are using more recent retryable, which changed the logger interface, then there's a conflict with that and v2. That's what this PR addresses. Thanks!

**Comment by maier** [comment]
I've released v2.2.6 to address and locked retryablehttp at v0.5.2, thanks for your patience. Originally the patch applied to retryablehttp 'master' and circonus-gometrics was using v0.5.0 which would break. Now that the Logger interface has been released it's all up-to-date.

**Comment by jefferai** [comment]
Thank you!

**Pull request closed without merging**
